baseURL = "http://localhost:1313/"
languageCode = "en"
defaultContentLanguage = "en"
title = "客舟听雨"   # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 6                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "hj24"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "好站"
  weight = 40
  identifier = "fav"
  url = "/fav/"
[[menu.main]]
  name = "代码片"
  weight = 50
  identifier = "snippets"
  url = "/snippets/"
[[menu.main]]
  name = "关于"
  weight = 60
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "hj24.life"                          # site's subTitle  # 网站二级标题
  footerSlogan = "hj24's life log"                # site's footer slogan  # 网站页脚标语
  keywords = ["Hugo","theme","zozo"]              # site's keywords  # 网站关键字
  description = "hj24's life log."                # site's description  # 网站描述
  enableMathJax = true                            # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                            # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  github = "https://github.com/hj24"
  zhihu = "https://www.zhihu.com/people/da-li-ju-13"
  # twitter = " "
  # facebook = " "
  # weibo = " "
  # instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
